project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercvise"
        menu:
          - text: "Hands-on Exercise 1"
          - href: "Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

